FROM docker.io/babashka/babashka:latest

LABEL org.opencontainers.image.source="https://github.com/timokramer/KubernetesSubmissions"
LABEL org.opencontainers.image.title="log-output"
LABEL org.opencontainers.image.description="mooc.fi course on kubernetes"
LABEL org.opencontainers.image.version="1.11"

COPY log-output.clj .
ENTRYPOINT ["bb", "log-output.clj"]
