FROM docker.io/babashka/babashka:latest

LABEL org.opencontainers.image.source="https://github.com/timokramer/KubernetesSubmissions"
LABEL org.opencontainers.image.title="pong-app"
LABEL org.opencontainers.image.description="mooc.fi course on kubernetes"
LABEL org.opencontainers.image.version="1.11"

COPY pong.clj .
ENTRYPOINT ["bb", "pong.clj"]
